POST http://localhost:3003/turmas
Content-Type: application/json

{
    "nome": "Hooks",
    "modulo": ""
}

###

GET http://localhost:3003/turmas

###

PUT http://localhost:3003/turmas/modulo
Content-Type: application/json

{
    "id": "1665065639604",
    "modulo": "4"
}